# Generated by Django 5.2.11 on 2026-02-23 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TasksApp', '0002_task_description_task_due_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='due_date',
        ),
    ]
